
positive_comments = [
    "Produto excelente, superou minhas expectativas!",
    "Muito bom, recomendo a todos!",
    "Ótima qualidade e entrega rápida.",
    "Adorei, funciona perfeitamente!",
    "Valeu cada centavo, estou muito satisfeito!",
    "Produto incrível, superou todas as minhas expectativas!",
    "Muito satisfeito, valeu cada centavo!",
    "Entrega rápida e produto de ótima qualidade!",
    "Perfeito! Exatamente como descrito no anúncio.",
    "Adorei! Funciona perfeitamente e é muito fácil de usar.",
    "A qualidade é excelente, recomendo a todos!",
    "Ótimo custo-benefício, compraria novamente!",
    "Melhor compra que fiz nos últimos tempos!",
    "O design é lindo e o material muito resistente!",
    "Super recomendo! Muito acima do esperado!",
    "Sensacional, cumpre tudo o que promete!",
    "Muito bom, a experiência de uso foi ótima!",
    "Chegou antes do prazo e em perfeito estado!",
    "Muito bem embalado e em perfeito funcionamento!",
    "Ótima escolha! Estou muito feliz com a compra.",
    "Simplesmente perfeito, atendeu todas as minhas necessidades!",
    "Produto de altíssima qualidade, fiquei impressionado!",
    "Excelente atendimento e um produto maravilhoso!",
    "O desempenho é incrível, melhor do que eu esperava!",
    "Resistente e funcional, uso todos os dias!",
    "Super fácil de usar e muito prático!",
    "Melhor investimento que fiz, super útil!",
    "Com certeza voltarei a comprar mais produtos dessa marca!",
    "Muito bonito e confortável, adorei!",
    "Perfeito para o que eu precisava, 100% satisfeito!",
    "Chegou direitinho, bem embalado e sem nenhum defeito!",
    "Ótima experiência de compra, nota 10!",
    "Já testei várias vezes e sempre funciona perfeitamente!",
    "Produto maravilhoso, vale muito a pena!",
    "A qualidade surpreendeu, melhor do que eu imaginava!"
]

neutral_comments = [
    "Produto razoável, nada de especial.",
    "Funciona como esperado, mas nada incrível.",
    "Entrega no prazo, mas qualidade mediana.",
    "Não é ruim, mas também não é ótimo.",
    "Atendeu às expectativas básicas.",
    "O produto é aceitável, mas não me impressionou.",
    "Não é ruim, mas também não é algo que eu compraria de novo.",
    "A qualidade é média, cumpre o que promete.",
    "Parece durável, mas ainda preciso testar mais.",
    "Chegou no prazo, embalagem estava intacta.",
    "Produto razoável, funciona como descrito.",
    "Não vi muita diferença em relação a outros similares.",
    "Entrega foi dentro do esperado, sem surpresas.",
    "O material poderia ser um pouco melhor, mas não é ruim.",
    "Bom custo-benefício, mas nada extraordinário.",
    "Não me arrependo da compra, mas esperava mais.",
    "A descrição corresponde ao produto, sem grandes destaques.",
    "Funciona bem, mas há opções melhores pelo mesmo preço.",
    "Parece ser um produto comum, nada fora do normal.",
    "Atende ao propósito, mas não supera expectativas.",
    "A cor e o tamanho são exatamente como na foto.",
    "Não notei defeitos, mas também não achei incrível.",
    "O desempenho é mediano, não se destaca.",
    "A experiência de uso é neutra, nem boa nem ruim.",
    "Aceitável pelo preço, mas há alternativas melhores.",
    "A qualidade não surpreende, mas também não decepciona.",
    "Produto correto, sem nenhum diferencial especial.",
    "Cumpre o que promete, mas esperava mais pelo valor.",
    "O acabamento poderia ser um pouco melhor.",
    "O design é simples, sem detalhes chamativos.",
    "A durabilidade parece boa, mas ainda estou testando.",
    "Para uso básico, atende bem.",
    "O manual poderia ser mais detalhado, mas dá para entender.",
    "A funcionalidade é normal, sem grandes destaques."
]

negative_comments = [
    "Péssima qualidade, não recomendo.",
    "Muito decepcionado, esperava mais.",
    "Quebrou depois de poucos dias de uso.",
    "Produto veio com defeito, experiência ruim.",
    "Não vale o preço, perdi dinheiro.",
    "Produto de péssima qualidade, não recomendo.",
    "Muito frágil, quebrou em poucos dias.",
    "Não vale o preço, dinheiro jogado fora.",
    "A entrega demorou muito, fiquei decepcionado.",
    "Material muito ruim, parece que vai quebrar fácil.",
    "Não funciona como prometido, propaganda enganosa!",
    "Chegou com defeito, tive que pedir reembolso.",
    "Fiquei frustrado, esperava algo muito melhor.",
    "O produto veio incompleto, faltam peças.",
    "Não atendeu às minhas expectativas, qualidade baixa.",
    "Péssima experiência de compra, não recomendo essa loja.",
    "A descrição não condiz com o que recebi.",
    "Muito difícil de usar, manual confuso.",
    "O acabamento é horrível, cheio de falhas.",
    "O produto veio riscado e parece usado.",
    "A embalagem estava toda amassada quando chegou.",
    "O suporte ao cliente foi péssimo, ninguém resolveu meu problema.",
    "Não durou nem um mês, muito decepcionado.",
    "Comprei esperando algo de qualidade, mas é muito inferior.",
    "A bateria acaba rápido demais, péssima autonomia.",
    "A montagem foi extremamente difícil, instruções ruins.",
    "Não funciona direito, trava o tempo todo.",
    "Muito barulhento, não dá para usar direito.",
    "A cor não é como na foto, bem diferente.",
    "Chegou atrasado e veio com defeitos.",
    "Tive que devolver, não gostei nada do produto.",
    "A conexão com outros dispositivos é horrível.",
    "O botão quebrou no primeiro uso.",
    "Parece um produto barato e mal feito.",
    "Não recomendo para ninguém, totalmente insatisfeito."
]


#konkretnie dla produktów: 
telephone_pt = [
    "A câmera deste celular é incrível! As fotos ficam muito nítidas.",
    "A bateria dura o dia inteiro, estou muito satisfeito.",
    "O design é muito bonito, mas o telefone é um pouco pesado.",
    "A tela tem cores vibrantes e o brilho é ótimo ao ar livre.",
    "O sistema operacional é muito rápido e fluido.",
    "A qualidade do áudio nos alto-falantes é impressionante.",
    "O reconhecimento facial funciona muito bem, mesmo no escuro.",
    "O carregamento rápido é realmente eficiente, em menos de uma hora está completo.",
    "A interface é intuitiva e fácil de usar.",
    "O preço é um pouco alto, mas vale a pena pelo desempenho.",
    "O telefone esquenta um pouco quando jogo por muito tempo.",
    "A câmera frontal poderia ser melhor, especialmente em pouca luz.",
    "A conectividade 5G é muito rápida e estável.",
    "A memória interna é suficiente para todos os meus aplicativos.",
    "O sensor de impressão digital é rápido e preciso.",
    "A resistência à água me dá mais segurança no uso diário.",
    "O GPS funciona perfeitamente e é muito preciso.",
    "O telefone é muito leve e confortável na mão.",
    "O processador é muito potente, não trava nunca.",
    "O telefone vem com muitos aplicativos pré-instalados desnecessários.",
    "A bateria descarrega rápido quando uso aplicativos pesados.",
    "A qualidade das chamadas é excelente, o microfone capta muito bem.",
    "O armazenamento poderia ser maior, falta espaço para minhas fotos.",
    "A tela grande facilita a leitura e assistir vídeos.",
    "O suporte ao cliente foi muito prestativo quando precisei de ajuda.",
    "A construção do aparelho parece muito resistente.",
    "O celular tem um bom custo-benefício.",
    "A câmera tem muitos modos e funcionalidades úteis.",
    "A duração da bateria poderia ser melhor.",
    "O carregador original é muito eficiente.",
    "O som nos fones de ouvido Bluetooth é muito claro.",
    "O telefone atualiza para a versão mais recente do sistema rapidamente.",
    "O sensor de proximidade às vezes não funciona direito.",
    "O brilho automático da tela não é muito preciso.",
    "O telefone tem um ótimo desempenho em jogos pesados.",
    "O tempo de resposta do touch é imediato.",
    "O design é elegante e sofisticado.",
    "O telefone tem uma ótima relação custo-benefício.",
    "A câmera traseira tem estabilização óptica, o que ajuda muito nos vídeos.",
    "O telefone suporta carregamento sem fio, o que é muito conveniente.",
    "O vidro traseiro deixa muitas marcas de dedo.",
    "A interface do usuário tem muitos recursos interessantes.",
    "O telefone é muito rápido para abrir aplicativos.",
    "A experiência de uso no dia a dia é excelente.",
    "O modo noturno da câmera faz um ótimo trabalho.",
    "O telefone é compatível com caneta stylus, o que é útil para anotações.",
    "A qualidade da imagem da tela OLED é impressionante.",
    "O telefone desbloqueia muito rápido com reconhecimento facial.",
    "A vibração do telefone poderia ser mais forte.",
    "A conectividade Wi-Fi é estável e rápida.",
    "O telefone tem uma excelente duração de bateria para vídeos em streaming."
]

robot_pt = [
    "O robô aspirador mudou minha vida! Agora minha casa está sempre limpa sem esforço.",
    "Muito eficiente, mas um pouco barulhento.",
    "Gostei bastante, mas poderia ter uma bateria mais duradoura.",
    "Excelente para quem tem pets! Remove todos os pelos sem problema.",
    "Adorei a função de mapeamento! Ele sabe exatamente onde limpar.",
    "Preço um pouco alto, mas vale cada centavo.",
    "Não substitui uma faxina completa, mas ajuda muito na manutenção da limpeza.",
    "Simples de usar e muito eficiente!",
    "A bateria dura bastante e ele volta sozinho para carregar.",
    "Meu melhor investimento do ano!",
    "Faz um bom trabalho, mas pode ficar preso em tapetes grossos.",
    "Facilita muito a vida de quem tem crianças pequenas.",
    "Gostaria que ele tivesse um reservatório maior para poeira.",
    "Perfeito para apartamentos pequenos!",
    "Inteligência artificial excelente, desvia bem dos obstáculos.",
    "Meu cachorro tem medo dele, mas eu adoro!",
    "Economizei muito tempo na limpeza da casa.",
    "O controle pelo aplicativo é muito prático.",
    "Silencioso e eficiente!",
    "Precisa de manutenção frequente, mas compensa.",
    "Limpa bem, mas poderia subir melhor em tapetes altos.",
    "Excelente custo-benefício!",
    "Design bonito e moderno.",
    "Adorei que ele volta sozinho para a base quando a bateria está baixa.",
    "Senti falta de uma função para esfregar o chão.",
    "Ele se perde de vez em quando, mas na maioria das vezes funciona bem.",
    "O sensor antiqueda funciona perfeitamente.",
    "Vale a pena para quem tem uma rotina corrida.",
    "Funciona muito bem em pisos frios.",
    "Ele tem dificuldade em cantos, mas no geral é ótimo.",
    "Mapeia bem os cômodos e evita bater nos móveis.",
    "A função de agendamento é muito útil.",
    "Supera as expectativas!",
    "Tem um pouco de dificuldade com fios espalhados pelo chão.",
    "Limpeza rápida e eficiente.",
    "Não é tão eficiente em tapetes muito felpudos.",
    "Excelente opção para idosos que não conseguem limpar com frequência.",
    "O app é intuitivo e fácil de configurar.",
    "A função de mop poderia ser mais potente.",
    "Aspira muito bem poeira e pequenos detritos.",
    "Um pouco caro, mas muito útil.",
    "Nunca mais precisei varrer a casa!",
    "Ajuda muito na rotina doméstica.",
    "É ótimo, mas poderia ser mais barato.",
    "Meu gato adora subir nele enquanto ele trabalha!",
    "Um bom investimento para quem tem alergia a pó.",
    "Poderia ter um pouco mais de potência de sucção.",
    "Ele se enrosca em fios, mas depois aprende a evitá-los.",
    "É um ótimo ajudante para a limpeza diária.",
    "Recomendo a todos que querem uma casa sempre limpa sem esforço!"
]

watch_pt = [
    "Design elegante e sofisticado, combina com qualquer roupa.",
    "Muito confortável no pulso, nem parece que estou usando.",
    "A bateria dura bastante, não preciso carregar com frequência.",
    "A precisão do relógio é excelente, nunca atrasa.",
    "O visor é grande e fácil de ler, mesmo sob luz forte.",
    "Os materiais são de alta qualidade, parece bem durável.",
    "Tem muitas funções úteis, como cronômetro e alarme.",
    "Resistente à água, posso usá-lo sem medo de molhar.",
    "A pulseira é ajustável e muito confortável.",
    "A iluminação noturna ajuda muito em ambientes escuros.",
    "O preço é justo pela qualidade oferecida.",
    "O mecanismo automático funciona perfeitamente.",
    "O vidro é resistente a riscos, ótimo para o dia a dia.",
    "O design clássico nunca sai de moda.",
    "Boa relação custo-benefício.",
    "A conectividade com o smartphone é muito prática.",
    "Leve e confortável, ideal para uso diário.",
    "As funções esportivas são muito úteis para quem pratica exercícios.",
    "Adoro a opção de troca de pulseira, fica sempre com um visual novo.",
    "Marca confiável, já tive outros modelos e nunca me decepcionaram.",
    "Ótima resistência, já caiu algumas vezes e continua perfeito.",
    "A caixa do relógio é bem construída e elegante.",
    "O acabamento em aço inoxidável dá um toque premium.",
    "Muito bonito e sofisticado, recebo vários elogios.",
    "A precisão do cronômetro é incrível.",
    "O carregamento sem fio é uma grande vantagem.",
    "Gostei do peso, não é muito leve nem muito pesado.",
    "A pulseira de couro dá um toque de classe.",
    "A resistência à água permite usar na piscina sem problemas.",
    "O ajuste no pulso é perfeito, não fica apertado nem frouxo.",
    "O visor digital tem excelente contraste.",
    "O sistema de notificações no smartwatch é muito útil.",
    "A bateria poderia durar um pouco mais, mas ainda é boa.",
    "A interface do relógio é intuitiva e fácil de navegar.",
    "O vidro safira evita arranhões indesejados.",
    "A durabilidade parece muito boa, já estou usando há meses.",
    "O fecho é seguro e não abre facilmente.",
    "A personalização do mostrador é um diferencial incrível.",
    "Ideal tanto para ocasiões formais quanto casuais.",
    "O sistema de carregamento rápido economiza tempo.",
    "A conectividade Bluetooth funciona sem problemas.",
    "O sensor de batimentos cardíacos é bem preciso.",
    "O GPS embutido é útil para atividades ao ar livre.",
    "A tela touch responde muito bem ao toque.",
    "As notificações de chamadas e mensagens são muito úteis.",
    "A possibilidade de trocar as pulseiras aumenta a versatilidade.",
    "O relógio combina com qualquer ocasião.",
    "A precisão dos sensores é impressionante.",
    "A construção robusta garante longa vida útil.",
    "Excelente compra, recomendo para todos!"
]
